# Generated by Django 4.2.6 on 2023-11-02 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_freinduser_invited_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreindUser',
            new_name='FriendUser',
        ),
    ]
