# Generated by Django 4.2.6 on 2023-11-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0003_rename_freinduser_frienduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frienduser',
            options={'verbose_name': 'User Friend', 'verbose_name_plural': 'User Friends'},
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Block User',
                'verbose_name_plural': 'Block Users',
            },
        ),
    ]
