# Generated by Django 4.2.5 on 2023-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accountverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_type',
            field=models.CharField(blank=True, choices=[('1', 'Normal'), ('2', 'Social')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
