# Generated by Django 4.2.6 on 2023-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_forgotpasswordandpasscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='public/bullet_proof//profile_pic'),
        ),
    ]
