# Generated by Django 4.2.6 on 2023-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
