# Generated by Django 4.2.6 on 2023-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_social_media_id_userprofile_platform_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
