# Generated by Django 4.2.6 on 2023-10-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Femal'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
