# Generated by Django 4.2.6 on 2023-10-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordandpasscode',
            name='is_passcode',
            field=models.BooleanField(default=False),
        ),
    ]
