# Generated by Django 4.2.6 on 2023-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_forgotpasswordandpasscode_is_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
