# Generated by Django 4.2.6 on 2023-11-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_userprofile_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='online_status',
            field=models.IntegerField(default=0),
        ),
    ]
